Starter class with abundance features
angelolab/SpaceCat pull request #2
Opened 2024-08-15 20:22 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

This PR includes starter code for the SpaceCat functionality. It addresses part of #1, but doesn't include any features other than the cell abundances (densities and density ratios).

**How did you implement your changes**

Laid out in #1. 
* preprocess.py contains functions for preparing the cell table for SpaceCat processing (i.e. adding functional marker positivity to the table, later will include distance matrix generation and more)
* features.py contains the FeatureSpace() class, which does all the heavy lifting for generating the intermediate stats tables and the final feature table

**Remaining issues**

- [ ] some more generalization of parameters
- [ ] add notebook and/or example code to the readme
- [ ] add some tests

2024-08-20 22:52 UTC, alex-l-kong requested changes
General coding practice comments to start off with.

2024-08-20 22:52 UTC, alex-l-kong commented on src/SpaceCat/features.py
> +        table_small = table.loc[:, ~table.columns.isin(drop_cols)]
Alternatively: `table_small = table.drop(columns=drop_cols, errors="ignore")` will bypass errors if a name in `drop_cols` doesn't exist.

2024-08-20 22:52 UTC, alex-l-kong commented on src/SpaceCat/features.py
> +            long_df = long_df.rename(columns={cluster_col_name: 'cell_type'})
The logic between the `if` and `else` clauses are different enough that I'd argue for making two separate helper functions.

2024-08-20 22:52 UTC, alex-l-kong commented on src/SpaceCat/features.py
> +            drop_cols_all = drop_cols_all + [subset_col]
```suggestion
        drop_cols_all = drop_cols + [subset_col] if subset_col is not None else drop_cols.copy()
```

2024-08-20 22:52 UTC, alex-l-kong commented on src/SpaceCat/features.py
> +                       cluster_stats=False, normalize=False, drop_cols=[],
Generally bad practice to pass in mutable types as default arguments. Setting `drop_cols=None` would be better.

2024-08-20 22:52 UTC, alex-l-kong commented on src/SpaceCat/features.py
> +        grouped_cell_freq_region['cell_type'] = 'all'
I'd argue for breaking down these three individual steps into helper functions.

2024-08-20 22:52 UTC, alex-l-kong commented on src/SpaceCat/features.py
> +        count_df['value'] = count_df['value'] * 1000
This step can also be broken down into a helper function. The `generate_cluster_stats` function is large right now, using helper functions will reduce code and help with flow.

2024-08-20 22:52 UTC, alex-l-kong commented on src/SpaceCat/features.py
> +                                                    compartment
If you really wanted to:

```suggestion
        compartment_df["feature_name_unique"] = compartment_df["feature_name"]
        if compartment != "all":
            compartment_df["feature_name_unique"] = compartment_df["feature_name_unique"] + "__" + compartment
```

2024-08-22 18:41 UTC, camisowers commented on src/SpaceCat/features.py
> +        grouped_cell_freq_region['cell_type'] = 'all'
Since this is the only instance the code is used, I just extracted the repetitive metadata assignment into a nested helper function.

2024-08-30 15:41 UTC, jranek requested changes
Looks awesome, super quick to run too :). Here are some initial thoughts for clarity

2024-08-30 15:41 UTC, jranek commented on src/SpaceCat/features.py
> +        self.cluster_columns = cluster_columns
It's also unclear that area for each compartment must have the same name as the compartment_col. This would be simpler if we provide the functions to compute compartments and ensure the naming convention is correct. Else, I think it needs to be more explicitly stated

2024-08-30 15:41 UTC, jranek commented on src/SpaceCat/features.py
> +        def add_metadata(panda_series, metric, compartment_col=False):
I might rename this to `add_feature_metadata` in case people think it's actual metadata

2024-08-30 15:41 UTC, jranek commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata_processed.uns['feature_metadata'].to_csv(os.path.join(output_dir, 'SpaceCat', 'feature_metadata.csv'))\n",
Is there a reason to have this saved separately? It's already included in the combined_feature_data, right?

2024-08-30 15:41 UTC, jranek commented on src/SpaceCat/features.py
> +        cell_table_clusters = self.adata_table.obs[
The naming convention is a bit hard to follow, I think it could benefit from more descriptions in text or within logging.info statements. Computing frequency and total abundance of cell types, computing the density, computing the ratios, etc. Abundance is used a bunch of times, but it's hard to follow since they're different types of abundances

2024-08-30 15:41 UTC, jranek commented on src/SpaceCat/features.py
> +    def combine_features(self, correlation_filtering=0.7):
This `correlation_filtering` param should be an init value for the user to change if they so choose. If False, then doesn't compute, else whatever value is set ensuring correct range

2024-08-30 15:41 UTC, jranek commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata_processed.uns['excluded_features'].to_csv(os.path.join(output_dir, 'SpaceCat', 'excluded_features.csv'))"
Would be helpful if excluded_features had a column that indicated where/why it was excluded. For example, correlation, density etc

2024-08-30 17:38 UTC, camisowers commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata.obs = pd.merge(cell_table.loc[:, cell_data_cols, ], on = ['fov'])\n",
Yeah this is where I meant to merge the Patient_ID and other metadata, nice catch!

2024-08-30 17:45 UTC, camisowers commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata_processed.uns['feature_metadata'].to_csv(os.path.join(output_dir, 'SpaceCat', 'feature_metadata.csv'))\n",
It is saved in combined_feature_data yes, but this is a much simpler output for users to look at and understand since it explains only unique features (e.g ~500 rows) rather than having the each feature repeated as a row for each image (~500,000 rows).

2024-08-30 18:13 UTC, camisowers commented on src/SpaceCat/features.py
> +    def combine_features(self, correlation_filtering=0.7):
Agreed I remembered to include this when doing the functional marker stats but hadn't ported it over yet!

2024-08-30 19:21 UTC, camisowers commented on src/SpaceCat/features.py
> +        cell_table_clusters = self.adata_table.obs[
I'll add some clarifying comments!

2024-08-30 20:18 UTC, jranek commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata_processed.uns['feature_metadata'].to_csv(os.path.join(output_dir, 'SpaceCat', 'feature_metadata.csv'))\n",
ah gotcha!

2024-08-30 22:00 UTC, camisowers commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata_processed = preprocess_table(adata, functional_marker_thresholds)\n",
I think we can just convert any sparse adata.X input to dense matrices for now, and if we have issues with storage we can revisit how the preprocessing functions work and maybe adapt them to work with sparse input.

2024-08-30 22:01 UTC, camisowers commented on src/SpaceCat/features.py
> +        self.cluster_columns = cluster_columns
For now I'll add in some if statements to ensure the image wide features get computed without issue and skip compartment specific stuff. Then we can always add in some preprocessing functions to take in masks and assign cells to individual compartments / compute the areas later!

2024-08-30 23:17 UTC, camisowers commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata_processed = preprocess_table(adata, functional_marker_thresholds)\n",
> Creating the single positive and double positive functional dfs throws a lot of frame insert fragmented df warnings. I think this can be circumvented if you append to a new df/ dictionary rather than doing the thresholding directly inside the existing dataframe

I don't get there warnings. 🤔 For now I'll leave the functions as they are, but once we have package versions set I'll try it again and see if it pops up!

2024-09-03 18:39 UTC, camisowers commented on src/SpaceCat/example_SpaceCat.ipynb
> +    "adata_processed.uns['excluded_features'].to_csv(os.path.join(output_dir, 'SpaceCat', 'excluded_features.csv'))"
Currently this is only correlation based filtered features, but as we incorporate more filtering for functional markers I'll think about keeping a running list with descriptions.

2024-09-03 22:45 UTC, jranek approved these changes
Looks good!!

2024-09-03 23:25 UTC, ngreenwald approved these changes
This was a ton of work! Great start

2024-09-03 23:26 UTC, merged