Readme improvements
angelolab/SpaceCat pull request #8
Opened 2024-09-18 20:09 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #5. Expands readme to include more detail about user inputs, as well as adds and example dataset.

**How did you implement your changes**

Pulled FOVs representing various patients and timepoints:

Patient_ID | fov | Timepoint
-- | -- | --
3 | TONIC_TMA22_R10C6 | baseline
3 | TONIC_TMA22_R11C3 | pre_nivo
31 | TONIC_TMA16_R6C5 | primary
31 | TONIC_TMA16_R6C6 | primary
31 | TONIC_TMA16_R8C3 | on_nivo
51 | TONIC_TMA13_R1C5 | pre_nivo
94 | TONIC_TMA4_R10C1 | baseline
94 | TONIC_TMA4_R10C4 | on_nivo
94 | TONIC_TMA4_R10C5 | pre_nivo
94 | TONIC_TMA4_R10C6 | pre_nivo
94 | TONIC_TMA4_R9C6 | baseline

None of these images contain any immune aggregate regions. 
Also included a small fix for a correlation error Kelly ran into. Occurs when there are not even feature values to calculate the spearmanr.

**Remaining issues**

N/A

2024-09-18 22:26 UTC, ngreenwald requested changes
Looks great, just a couple small changes

2024-09-18 22:26 UTC, ngreenwald commented on README.md
>  The required variables are:
I think we should try and have these variable names line up with the names in the `AnnData Conversion` section. That way, we only have to list/explain them once, and it will be consistent throughout the readme. 

It might even be the case that we don't need to have separate sections listing them, and can just refer to previous description? Let me know what you think.

2024-09-18 22:26 UTC, ngreenwald commented on README.md
> +Each of the features are computed at two region levels, image-wide and within individual compartments (if specified).
```suggestion
All features are computed separately in each image. In addition, if you provided optional compartment assignments, the features will also be computed within each compartment.
```

2024-09-18 22:26 UTC, ngreenwald commented on README.md
> +  - Using a minimum density threshold for ratios, if both cell densities were below the threshold, the ratio for that image was not calculated.
I think we can have a separate section that talks about when features are not calculated. For this high-level summary in the readme, I think we can skip it

2024-09-18 22:26 UTC, ngreenwald commented on README.md
> +- `functional_marker`: For each cell type/functional marker combination, the proportion of cells above the marker-specific threshold was calculated.
```suggestion
- `functional_marker`: For each cell type/functional marker combination, the proportion of cells positive for that marker, using the supplied marker-specific thresholds to determine positivity.
```

2024-09-18 22:26 UTC, ngreenwald commented on README.md
> +  - Marker frequencies were not computed for regions with fewer than a set minimum number of cells.
same thing here, can remove the minimum cells info

2024-09-18 22:26 UTC, ngreenwald commented on src/SpaceCat/features.py
> +                    continue
Can you explain again what this is doing? And should we replace 3 with a reference to the number of unique compartments?

2024-09-19 18:04 UTC, camisowers commented on README.md
>  cell_table = pd.merge(cell_table, metadata, on=['fov'])
Yeah we could definitely just append it at the end.
We can either add the metadata as it's own dataframe in adata.uns['metadata'] or just merge it with the combined_feature_data tables. This would be guidance code in the readme, no need to build it into the SpaceCat functions.

2024-09-19 18:39 UTC, camisowers commented on src/SpaceCat/features.py
> +                    continue
I've just adjusted this check after digging through [scipy's code](https://github.com/scipy/scipy/blob/446160a1395cfd2e54a3c4cfe00fd712db8f324e/scipy/stats/_mstats_basic.py#L684) a bit more. To generate a correlation value for a feature between two compartments, that feature needs to appear in both the image and specific compartment in at least 3 fovs. Kelly ran into this and so did I when running the example data, since there are only 11 fovs.

2024-09-19 19:45 UTC, ngreenwald commented on src/SpaceCat/features.py
> +                    continue
Got it, that makes sense. Correlation would be undefined for just two values

2024-09-19 19:52 UTC, camisowers commented on README.md
>  The required variables are:
I agree, having the information twice is a bit overkill, but I wanted to make sure the arg names were specified down here for the user. Jolene suggested using the `_key` format to align with what scanpy/squidpy does, so let me see if I can condense the two sections.

2024-09-20 01:05 UTC, ngreenwald approved these changes
Looks good!

2024-09-20 01:06 UTC, merged